# Generated by Django 4.1.1 on 2022-10-27 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='codadministrador',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='usuario',
        ),
    ]
