# Generated by Django 4.1.1 on 2022-11-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0003_alter_materia_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='horario',
        ),
    ]
