# Generated by Django 4.1.1 on 2022-11-10 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_alter_tienen_unique_together_remove_tienen_codgrupo_and_more'),
        ('profesores', '0004_remove_materia_horario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materia',
            old_name='cod_profesor',
            new_name='usuarioCI',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='codProfesor',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='usuarioci',
        ),
        migrations.AddField(
            model_name='lista',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materia',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='usuario_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administracion.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lista',
            name='codLista',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='codMateria',
            field=models.IntegerField(unique=True),
        ),
    ]
