# Generated by Django 4.1.2 on 2022-10-23 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0002_grupo_rename_contrasenia_administrador_contraseña_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('codAlumno', models.IntegerField(primary_key=True, serialize=False)),
                ('numPadre', models.CharField(max_length=255)),
                ('foto', models.CharField(max_length=255)),
                ('mac', models.CharField(max_length=255)),
                ('cedula', models.IntegerField(unique=True)),
                ('usuario', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=70, unique=True)),
                ('codadministrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.administrador')),
                ('usuarioci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.usuario')),
            ],
        ),
    ]
