# Generated by Django 4.1.2 on 2022-10-23 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='apellido',
            new_name='fotoAlumno',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='codadministrador',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='email',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='usuario',
        ),
    ]
