# Generated by Django 4.1.2 on 2022-10-23 06:09

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('codGrupo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='administrador',
            old_name='Contrasenia',
            new_name='contraseña',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='cod_administrador',
            new_name='codAdministrador',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Contrasenia',
            new_name='contraseña',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='cod_administrador',
        ),
        migrations.AddField(
            model_name='administrador',
            name='codAdministrador',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Estan',
            fields=[
                ('codGrupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='administracion.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Pasan',
            fields=[
                ('codGrupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='administracion.grupo')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tienen',
            fields=[
                ('codGrupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='administracion.grupo')),
            ],
        ),
    ]
