# Generated by Django 4.1.2 on 2022-10-23 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_grupo_rename_contrasenia_administrador_contraseña_and_more'),
        ('alumnos', '0001_initial'),
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='alumnos',
            field=models.ManyToManyField(to='alumnos.alumno'),
        ),
        migrations.AddField(
            model_name='tienen',
            name='codProfesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesores.profesor'),
        ),
        migrations.AddField(
            model_name='pasan',
            name='codLista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesores.lista'),
        ),
        migrations.AddField(
            model_name='pasan',
            name='codProfesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesores.profesor'),
        ),
        migrations.AddField(
            model_name='estan',
            name='codAlumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno'),
        ),
        migrations.AlterUniqueTogether(
            name='tienen',
            unique_together={('codGrupo', 'codProfesor')},
        ),
        migrations.AlterUniqueTogether(
            name='pasan',
            unique_together={('codGrupo', 'codProfesor', 'codLista')},
        ),
        migrations.AlterUniqueTogether(
            name='estan',
            unique_together={('codGrupo', 'codAlumno')},
        ),
    ]
