# Generated by Django 4.1.1 on 2022-10-25 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_remove_usuario_codadministrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codAdministrador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administracion.administrador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administrador',
            name='codAdministrador',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
