# Generated by Django 4.1.1 on 2022-10-26 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_usuario_codadministrador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estan',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pasan',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tienen',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estan',
            name='codGrupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.grupo'),
        ),
        migrations.AlterField(
            model_name='pasan',
            name='codGrupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.grupo'),
        ),
        migrations.AlterField(
            model_name='tienen',
            name='codGrupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.grupo'),
        ),
    ]
