# Generated by Django 4.1.1 on 2022-11-10 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alter_alumno_fotoalumno'),
        ('administracion', '0006_estan_id_pasan_id_tienen_id_alter_estan_codgrupo_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tienen',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tienen',
            name='codGrupo',
        ),
        migrations.RemoveField(
            model_name='tienen',
            name='codProfesor',
        ),
        migrations.RenameField(
            model_name='pasan',
            old_name='codGrupo',
            new_name='nombreGrupo',
        ),
        migrations.AlterUniqueTogether(
            name='pasan',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='codAdministrador',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='alumnos',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='codGrupo',
        ),
        migrations.AddField(
            model_name='administrador',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupo',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pasan',
            name='usuarioCI',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administrador',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.IntegerField(unique=True),
        ),
        migrations.DeleteModel(
            name='Estan',
        ),
        migrations.DeleteModel(
            name='Tienen',
        ),
        migrations.RemoveField(
            model_name='pasan',
            name='codProfesor',
        ),
    ]
