# Generated by Django 4.1.1 on 2022-11-10 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_alter_tienen_unique_together_remove_tienen_codgrupo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='codAdministrador',
        ),
    ]
